### ISSUE TITLE
Firebase Auth with Gatsby

### ISSUE THREAD

**Issue by mikenieva** [myTDC/tdc-works#1]
Hi @IadityaM.

I was wondering if you could solve your issue with dependencies into Gatsby for using Firebase.

I am trying to implement Firebase Auth in Gatsby, but it has been nearly impossible and I am looking if there is any repo with a successful installation.

Did you have success installing Gatsby and Firebase? 

Thank u.

**Comment by IadityaM** [comment]
> Hi @IadityaM.
> 
> I was wondering if you could solve your issue with dependencies into Gatsby for using Firebase.
> 
> I am trying to implement Firebase Auth in Gatsby, but it has been nearly impossible and I am looking if there is any repo with a successful installation.
> 
> Did you have success installing Gatsby and Firebase?
> 
> Thank u.

I'd encountered no errors when installing Firebase on top of the gatsby-default-starter.
The only difference was that the initialization of the components of firebase had to be done on demand - just put the inti code in a function and called the function on app init.
